apiVersion: v1
kind: Pod
metadata:
  name: pod-without-config-secret
spec:
  containers:
  - name: test-container
    image: nginx
    env:
    # - name: DB_USER
    #   value: "admin"        # directly hard-coded value
    # - name: DB_PASSWORD
    #   value: "password123"  # directly hard-coded value


--- 


apiVersion: v1
kind: Pod
metadata:
  name: pod-with-configmap
spec:
  containers:
  - name: test-container
    image: nginx
    env:
    - name: DB_USER
      valueFrom:
        configMapKeyRef:
          name: my-vars
          key: DB_USER
    - name: DB_PASSWORD
      valueFrom:
        configMapKeyRef:
          name: my-vars
          key: DB_PASSWORD



--- 
apiVersion: v1
kind: Secret
metadata:
  name: my-secret-vars
type: Opaque
data:
  DB_USER: YWRtaW4=          # base64 of "admin"
  DB_PASSWORD: cGFzc3dvcmQxMjM=   # base64 of "password123"

--- 
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-secret
spec:
  containers:
  - name: test-container
    image: nginx
    env:
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: my-secret-vars
          key: DB_USER
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: my-secret-vars
          key: DB_PASSWORD
